apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: demo-fe:/Service:dev-vm/demo-fe-service
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"demo-fe:/Service:dev-vm/demo-fe-service"},"name":"demo-fe-service","namespace":"dev-vm"},"spec":{"ports":[{"nodePort":30180,"port":80,"protocol":"TCP","targetPort":80}],"selector":{"app":"demo-frontend"},"type":"NodePort"}}
  creationTimestamp: "2026-02-23T04:55:01Z"
  name: demo-fe-service
  namespace: dev-vm
  resourceVersion: "10443917"
  uid: 199b7b8d-5518-47a7-926b-bc353a59c51f
spec:
  clusterIP: 10.110.160.207
  clusterIPs:
  - 10.110.160.207
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30180
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: demo-frontend
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
