apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"dev-integration-svc","namespace":"dev-vm"},"spec":{"ports":[{"name":"http8080","nodePort":32380,"port":8080,"protocol":"TCP","targetPort":8080}],"selector":{"app":"dev-integration"},"type":"NodePort"}}
  creationTimestamp: "2026-01-23T04:51:47Z"
  name: dev-integration-svc
  namespace: dev-vm
  resourceVersion: "1769084"
  uid: a7ed5aa6-f3f6-40f8-abc2-da32833668c8
spec:
  clusterIP: 10.99.202.220
  clusterIPs:
  - 10.99.202.220
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http8080
    nodePort: 32380
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: dev-integration
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
