apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"dev-was-svc","namespace":"dev-vm"},"spec":{"ports":[{"name":"ssh","nodePort":32122,"port":22,"targetPort":22},{"name":"http8080","nodePort":32180,"port":8080,"targetPort":8080}],"selector":{"app":"dev-was"},"type":"NodePort"}}
  creationTimestamp: "2026-01-19T10:43:22Z"
  name: dev-was-svc
  namespace: dev-vm
  resourceVersion: "807000"
  uid: a406d1f8-3727-46af-b764-e533a7d19006
spec:
  clusterIP: 10.103.101.169
  clusterIPs:
  - 10.103.101.169
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: ssh
    nodePort: 32122
    port: 22
    protocol: TCP
    targetPort: 22
  - name: http8080
    nodePort: 32180
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: dev-was
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
