apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"iwon-pvc","namespace":"dev-vm"},"spec":{"accessModes":["ReadWriteMany"],"resources":{"requests":{"storage":"10Gi"}},"storageClassName":"nfs-client"}}
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: cluster.local/nfs-provisioner-nfs-subdir-external-provisioner
    volume.kubernetes.io/storage-provisioner: cluster.local/nfs-provisioner-nfs-subdir-external-provisioner
  creationTimestamp: "2026-03-11T01:11:55Z"
  finalizers:
  - kubernetes.io/pvc-protection
  name: iwon-pvc
  namespace: dev-vm
  resourceVersion: "15159877"
  uid: fce63bf4-453c-4dfa-96f7-43b26df37ee3
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-client
  volumeMode: Filesystem
  volumeName: pvc-fce63bf4-453c-4dfa-96f7-43b26df37ee3
status:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  phase: Bound
