server:
  serviceType: NodePort
  servicePort: 2746
  serviceNodePort: 32746

controller:
  workflowNamespaces:
    - argo
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 512Mi

executor:
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      memory: 256Mi

artifactRepository:
  archiveLogs: true

singleNamespace: false
